// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: trace.proto

package scyna_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogCreatedSignal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time  uint64 `protobuf:"varint,1,opt,name=Time,proto3" json:"Time,omitempty"`
	ID    uint64 `protobuf:"varint,4,opt,name=ID,proto3" json:"ID,omitempty"`
	SEQ   uint64 `protobuf:"varint,5,opt,name=SEQ,proto3" json:"SEQ,omitempty"`
	Text  string `protobuf:"bytes,3,opt,name=Text,proto3" json:"Text,omitempty"`
	Level uint32 `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`
}

func (x *LogCreatedSignal) Reset() {
	*x = LogCreatedSignal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trace_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogCreatedSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogCreatedSignal) ProtoMessage() {}

func (x *LogCreatedSignal) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogCreatedSignal.ProtoReflect.Descriptor instead.
func (*LogCreatedSignal) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{0}
}

func (x *LogCreatedSignal) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *LogCreatedSignal) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *LogCreatedSignal) GetSEQ() uint64 {
	if x != nil {
		return x.SEQ
	}
	return 0
}

func (x *LogCreatedSignal) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *LogCreatedSignal) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type TraceCreatedSignal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ParentID  uint64 `protobuf:"varint,2,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	Type      uint32 `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Time      uint64 `protobuf:"varint,4,opt,name=Time,proto3" json:"Time,omitempty"`
	Duration  uint64 `protobuf:"varint,5,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Path      string `protobuf:"bytes,6,opt,name=Path,proto3" json:"Path,omitempty"`
	SessionID uint64 `protobuf:"varint,8,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Status    uint32 `protobuf:"varint,9,opt,name=Status,proto3" json:"Status,omitempty"`
	Source    string `protobuf:"bytes,10,opt,name=Source,proto3" json:"Source,omitempty"`
}

func (x *TraceCreatedSignal) Reset() {
	*x = TraceCreatedSignal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trace_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TraceCreatedSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceCreatedSignal) ProtoMessage() {}

func (x *TraceCreatedSignal) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceCreatedSignal.ProtoReflect.Descriptor instead.
func (*TraceCreatedSignal) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{1}
}

func (x *TraceCreatedSignal) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *TraceCreatedSignal) GetParentID() uint64 {
	if x != nil {
		return x.ParentID
	}
	return 0
}

func (x *TraceCreatedSignal) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *TraceCreatedSignal) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *TraceCreatedSignal) GetDuration() uint64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TraceCreatedSignal) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TraceCreatedSignal) GetSessionID() uint64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *TraceCreatedSignal) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TraceCreatedSignal) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type EndpointDoneSignal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceID   uint64 `protobuf:"varint,1,opt,name=TraceID,proto3" json:"TraceID,omitempty"`
	Status    int32  `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Response  string `protobuf:"bytes,3,opt,name=Response,proto3" json:"Response,omitempty"`
	Request   string `protobuf:"bytes,4,opt,name=Request,proto3" json:"Request,omitempty"`
	SessionID uint64 `protobuf:"varint,5,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
}

func (x *EndpointDoneSignal) Reset() {
	*x = EndpointDoneSignal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trace_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndpointDoneSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointDoneSignal) ProtoMessage() {}

func (x *EndpointDoneSignal) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointDoneSignal.ProtoReflect.Descriptor instead.
func (*EndpointDoneSignal) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{2}
}

func (x *EndpointDoneSignal) GetTraceID() uint64 {
	if x != nil {
		return x.TraceID
	}
	return 0
}

func (x *EndpointDoneSignal) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EndpointDoneSignal) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *EndpointDoneSignal) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *EndpointDoneSignal) GetSessionID() uint64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

var File_trace_proto protoreflect.FileDescriptor

var file_trace_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x63, 0x79, 0x6e, 0x61, 0x22, 0x72, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03,
	0x53, 0x45, 0x51, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x53, 0x45, 0x51, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x65,
	0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0xe6, 0x01, 0x0a, 0x12, 0x54, 0x72, 0x61,
	0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x22, 0x9a, 0x01, 0x0a, 0x12, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x6f,
	0x6e, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x63,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x54, 0x72, 0x61, 0x63, 0x65,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x42, 0x2f,
	0x0a, 0x0b, 0x73, 0x63, 0x79, 0x6e, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x02, 0x50,
	0x01, 0x5a, 0x0e, 0x2e, 0x2f, 0x3b, 0x73, 0x63, 0x79, 0x6e, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0xaa, 0x02, 0x0b, 0x73, 0x63, 0x79, 0x6e, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trace_proto_rawDescOnce sync.Once
	file_trace_proto_rawDescData = file_trace_proto_rawDesc
)

func file_trace_proto_rawDescGZIP() []byte {
	file_trace_proto_rawDescOnce.Do(func() {
		file_trace_proto_rawDescData = protoimpl.X.CompressGZIP(file_trace_proto_rawDescData)
	})
	return file_trace_proto_rawDescData
}

var file_trace_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_trace_proto_goTypes = []interface{}{
	(*LogCreatedSignal)(nil),   // 0: scyna.LogCreatedSignal
	(*TraceCreatedSignal)(nil), // 1: scyna.TraceCreatedSignal
	(*EndpointDoneSignal)(nil), // 2: scyna.EndpointDoneSignal
}
var file_trace_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trace_proto_init() }
func file_trace_proto_init() {
	if File_trace_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trace_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogCreatedSignal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trace_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TraceCreatedSignal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trace_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndpointDoneSignal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trace_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trace_proto_goTypes,
		DependencyIndexes: file_trace_proto_depIdxs,
		MessageInfos:      file_trace_proto_msgTypes,
	}.Build()
	File_trace_proto = out.File
	file_trace_proto_rawDesc = nil
	file_trace_proto_goTypes = nil
	file_trace_proto_depIdxs = nil
}
